name: "OWASP ZAP Scan Plan"

env:
  target: "http://juice-shop:3000"
  contexts:
    - name: "mainContext"
      urls:
        - "${target}"
      includePaths:
        - "${target}.*"
      excludePaths: []

jobs:
  - type: "passiveScan-config"
    parameters:
      maxAlertsPerRule: 0

  - type: "spider"
    parameters:
      context: "mainContext"
      url: "${target}"

  - type: "spiderAjax"
    parameters:
      context: "mainContext"
      url: "${target}"
      maxDuration: 5

  - type: "activeScan"
    parameters:
      context: "mainContext"

  - type: "report"
    parameters:
      title: "ZAP Security Scan Report"
      formats:
        - "json"
        - "html"
        - "xml"