name: "OWASP ZAP Scan Plan"

env:
  target: "http://juice-shop:3000"

jobs:
  - type: "passiveScan-config"
    parameters:
      maxAlertsPerRule: 0

  - type: "spider"
    parameters:
      url: "${env.target}"
      maxDepth: 10

  - type: "spiderAjax"
    parameters:
      url: "${env.target}"
      maxDuration: 5

  - type: "activeScan"
    parameters:
      url: "${env.target}"

  - type: "report"
    parameters:
      title: "ZAP Security Scan Report"
      formats:
        - "json"
        - "html"
        - "xml"