name: Test ZAP Downloader (pnpm)

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test-zap-downloader-pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable Corepack + pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate

      - name: Install project dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Run offline pack
        run: pnpm zap-downloader offline pack -o zap-offline.tar

      - name: Run offline unpack
        run: pnpm zap-downloader offline unpack -i zap-offline.tar -o zap-workspace

      - name: Start ZAP Daemon
        run: pnpm daemon:start -t zap-workspace/workspace/default.toml
